# Generated by Django 5.0.6 on 2024-05-29 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0002_remove_booking_seat_number_remove_seat_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='schedule_seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Bus.scheduleseat'),
        ),
    ]
