# Generated by Django 4.2.13 on 2024-06-05 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0003_alter_booking_schedule_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
