# Generated by Django 4.2.13 on 2024-06-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0004_booking_qr_code_alter_booking_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
