# Generated by Django 4.2.13 on 2024-06-05 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bus', '0005_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_boarded', models.BooleanField(default=False)),
                ('is_alighted', models.BooleanField(default=False)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Bus.schedule')),
                ('schedule_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Bus.scheduleseat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
